config_file_version: 1.0.0

data_dir: /home/hpinkard_waller/2tb_ssd

data:
  batch: 0
  dataset_name: "BSCCM"
  image_dim: 128
  channels:
  - DPC_Top
  - DPC_Bottom
  - DPC_Right
  - DPC_Left
  contrast_types:
  - led_array
  - led_array
  - led_array
  - led_array
  use_two_spectrum_unmixing: true

hyperparameters:
  arch: "DN121"
  mixture_type: "logistic"
  batch_size: 5
  change_input_channels: true
  density_output: true
  learning_rate: 5.4226696982933566e-05
  loss_weights:
    CD123: 1.0
    CD14: 1.0
    CD16: 1.0
    CD19: 1.0
    CD3: 1.0
    CD45: 1.0
    CD56: 1.0
    HLA-DR: 1.0
  max_epochs: 50000
  num_mixture_components: 19
  optimizer: ADAM
  overshoot_epochs: 20
  steps_per_epoch: 4000
  test_fraction: 0.05
  validation_fraction: 0.05
  
# Not read, generated automatically during training
training:
  tensorboard_dir: /home/hpinkard_waller/2tb_ssd/models/test/tensorboard/
